spring:
  application:
    name: car-dealer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: classpath:db/testdata.sql
  h2:
    console:
      enabled: true

server:
  port: 8082